package inaction.onetoone;

// Generated 2013/01/13 13:40:52 by Hibernate Tools 3.4.0.CR1

/**
 * UserOnetoone generated by hbm2java
 */
public class UserOnetoone implements java.io.Serializable {

	private long userId;
	private AddressOnetoone homeAddress;
	private AddressOnetoone billingAddress;
	private String username;
	private Long version;

	public UserOnetoone() {
	}

	public UserOnetoone(long userId) {
		this.userId = userId;
	}

	public UserOnetoone(long userId, AddressOnetoone addressOnetoone,
			String username) {
		this.userId = userId;
		this.homeAddress = addressOnetoone;
		this.username = username;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public AddressOnetoone getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(AddressOnetoone address) {
		this.homeAddress = address;
	}

	public AddressOnetoone getBillingAddress() {
		return billingAddress;
	}

	public void setBillingAddress(AddressOnetoone billingAddress) {
		this.billingAddress = billingAddress;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
}
