package manytomany;

// Generated 2013/01/30 19:47:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ItemCategoryMappingExtend generated by hbm2java
 */
public class ItemCategoryMappingExtend implements java.io.Serializable {

	private long mappingId;
	private Long version;
	private ItemManytomany itemManytomany;
	private CategoryManytomany categoryManytomany;
	private Date createdDate;
	private String userName;

	public ItemCategoryMappingExtend() {
	}

	public ItemCategoryMappingExtend(long mappingId,
			ItemManytomany itemManytomany, CategoryManytomany categoryManytomany) {
		this.mappingId = mappingId;
		this.itemManytomany = itemManytomany;
		this.categoryManytomany = categoryManytomany;
	}

	public ItemCategoryMappingExtend(long mappingId,
			ItemManytomany itemManytomany,
			CategoryManytomany categoryManytomany, Date createdDate,
			String userName) {
		this.mappingId = mappingId;
		this.itemManytomany = itemManytomany;
		this.categoryManytomany = categoryManytomany;
		this.createdDate = createdDate;
		this.userName = userName;
	}

	public long getMappingId() {
		return this.mappingId;
	}

	public void setMappingId(long mappingId) {
		this.mappingId = mappingId;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public ItemManytomany getItemManytomany() {
		return this.itemManytomany;
	}

	public void setItemManytomany(ItemManytomany itemManytomany) {
		this.itemManytomany = itemManytomany;
	}

	public CategoryManytomany getCategoryManytomany() {
		return this.categoryManytomany;
	}

	public void setCategoryManytomany(CategoryManytomany categoryManytomany) {
		this.categoryManytomany = categoryManytomany;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
