package fetch;

// Generated 2013/01/14 18:01:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FetchSub1 generated by hbm2java
 */
public class FetchSub1 implements java.io.Serializable {

	private long id;
	private Integer version;
	private FetchRoot fetchRoot;
	private String value;
	private Set fetchSub2s = new HashSet(0);

	public FetchSub1() {
	}

	public FetchSub1(long id, FetchRoot fetchRoot) {
		this.id = id;
		this.fetchRoot = fetchRoot;
	}

	public FetchSub1(long id, FetchRoot fetchRoot, String value, Set fetchSub2s) {
		this.id = id;
		this.fetchRoot = fetchRoot;
		this.value = value;
		this.fetchSub2s = fetchSub2s;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public FetchRoot getFetchRoot() {
		return this.fetchRoot;
	}

	public void setFetchRoot(FetchRoot fetchRoot) {
		this.fetchRoot = fetchRoot;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Set getFetchSub2s() {
		return this.fetchSub2s;
	}

	public void setFetchSub2s(Set fetchSub2s) {
		this.fetchSub2s = fetchSub2s;
	}

}
