package fetch;

// Generated 2013/01/14 18:01:45 by Hibernate Tools 3.4.0.CR1

/**
 * FetchSub2 generated by hbm2java
 */
public class FetchSub2 implements java.io.Serializable {

	private long id;
	private Integer version;
	private FetchSub1 fetchSub1;
	private String value;

	public FetchSub2() {
	}

	public FetchSub2(long id, FetchSub1 fetchSub1) {
		this.id = id;
		this.fetchSub1 = fetchSub1;
	}

	public FetchSub2(long id, FetchSub1 fetchSub1, String value) {
		this.id = id;
		this.fetchSub1 = fetchSub1;
		this.value = value;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public FetchSub1 getFetchSub1() {
		return this.fetchSub1;
	}

	public void setFetchSub1(FetchSub1 fetchSub1) {
		this.fetchSub1 = fetchSub1;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
