package inaction.generator;

// Generated 2013/01/14 1:11:15 by Hibernate Tools 3.4.0.CR1

/**
 * IdentityGenerator generated by hbm2java
 */
public class IdentityGenerator implements java.io.Serializable {

	private int id;
	private Long version;
	private String value;

	public IdentityGenerator() {
	}

	public IdentityGenerator(int id) {
		this.id = id;
	}

	public IdentityGenerator(int id, String value) {
		this.id = id;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
