package inaction.valuecollection;

// Generated 2013/01/06 14:25:01 by Hibernate Tools 3.4.0.CR1

import inaction.association.Item;

import java.util.Date;

/**
 * ItemImage generated by hbm2java
 */
public class ItemImage implements java.io.Serializable {

	private long imageId;
	private Integer version;
	private Item item;
	private String fileName;
	private Date createdDate;

	public ItemImage() {
	}

	public ItemImage(long imageId, Item item, String fileName) {
		this.imageId = imageId;
		this.item = item;
		this.fileName = fileName;
	}

	public ItemImage(long imageId, Item item, String fileName, Date createdDate) {
		this.imageId = imageId;
		this.item = item;
		this.fileName = fileName;
		this.createdDate = createdDate;
	}

	public long getImageId() {
		return this.imageId;
	}

	public void setImageId(long imageId) {
		this.imageId = imageId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
